# Generated by Django 5.0.6 on 2024-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_is_paid_order_order_number'),
        ('store_app', '0013_cartitems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='store_app.cartitems'),
        ),
    ]
