# Generated by Django 5.0.6 on 2024-06-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
