# Generated by Django 5.0.6 on 2024-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
