# Generated by Django 5.0.6 on 2024-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
