# Generated by Django 5.0.6 on 2024-06-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_availabledesign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
