# Generated by Django 5.0.6 on 2024-05-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
