# Generated by Django 5.0.6 on 2024-06-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_cartitems_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=50)),
                ('minimun_amount', models.IntegerField(default=500)),
                ('discount_amount', models.IntegerField(default=100)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
