# Generated by Django 5.0.6 on 2024-05-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Images'),
        ),
    ]
