# Generated by Django 5.0.6 on 2024-06-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimun_amount',
            new_name='minimum_amount',
        ),
    ]
